class CommandError(Exception):
    """Raised when a command fails due to user error"""
    pass